import { resolveCoreNavLabel } from '@/utils/coreNavLabel'
import type { TutorialBuildContext, TutorialStep } from '../types'
import { createStep } from '../stepFactory'

export function buildBasicSteps(ctx: TutorialBuildContext): TutorialStep[] {
  const { industryId, mods } = ctx
  const chatLabel = resolveCoreNavLabel('chat', industryId, mods) || '智能对话'
  const dataSourcesLabel = resolveCoreNavLabel('data-sources', industryId, mods) || '数据来源'
  const settingsLabel = resolveCoreNavLabel('settings', industryId, mods) || '系统设置'

  return [
    createStep({
      id: 'chat-entry',
      title: `${chatLabel}入口`,
      description: `请点击左侧「${chatLabel}」，从这里进入日常业务主流程`,
      targetSelector: '.sidebar .menu-item[data-view="chat"]',
      actionType: 'click',
      routeName: 'chat',
    }),
    createStep({
      id: 'starter-pack-open-tab',
      title: '打开「新手对话包」',
      description: '请先点击副窗顶部的「新手对话包」标签，切换到对话包列表后，再按后面步骤逐条点…',
      targetSelector:
        '[data-tutorial-spotlight="assistant-panel"] .assistant-tab[data-tutorial-id="tab-starterPack"]',
      actionType: 'click',
      routeName: 'chat',
      assistantTab: 'push',
      allowCardNext: true,
    }),
    createStep({
      id: 'starter-pack-demo-1-pick',
      title: '示例一 · 点选话术',
      description: '请点击第一条「查产品价格」示例。系统会跳到智能对话并把话术填入输入框。',
      targetSelector: '.assistant-body-starter .starter-pack-list > .starter-pack-item:nth-child(1)',
      actionType: 'click',
      routeName: 'chat',
      assistantTab: 'starterPack',
    }),
    createStep({
      id: 'starter-pack-demo-1-send',
      title: '示例一 · 发送',
      description: '请确认输入框内容无误后，点击下方「发送」按钮，把话术发给助手。',
      targetSelector: '#sendMessageBtn',
      actionType: 'click',
      routeName: 'chat',
    }),
    createStep({
      id: 'starter-pack-demo-1-view',
      title: '示例一 · 查看产品副窗',
      description: '本条是查价示例：发送后助手会打开「协助副窗」并带入查询结果',
      targetSelector: '[data-tutorial-assistant-body]',
      highlightSelector: '[data-tutorial-assistant-body]',
      actionType: 'observe',
      routeName: 'chat',
      assistantTab: 'assistant',
    }),
    createStep({
      id: 'starter-pack-demo-2-pick',
      title: '示例二 · 点选话术',
      description: '请回到副窗「新手对话包」，点击第二条「生成发货单单产品」示例。',
      targetSelector: '.assistant-body-starter .starter-pack-list > .starter-pack-item:nth-child(2)',
      actionType: 'click',
      routeName: 'chat',
      assistantTab: 'starterPack',
    }),
    createStep({
      id: 'starter-pack-demo-2-send',
      title: '示例二 · 发送',
      description: '点击下方「发送」，观察单产品发货单类话术如何被处理。',
      targetSelector: '#sendMessageBtn',
      actionType: 'click',
      routeName: 'chat',
    }),
    createStep({
      id: 'starter-pack-demo-3-pick',
      title: '示例三 · 点选话术',
      description: '进入本步后，教程会自动打开副窗并切到「新手对话包」',
      targetSelector: '.assistant-body-starter .starter-pack-list > .starter-pack-item:nth-child(3)',
      actionType: 'click',
      routeName: 'chat',
      assistantTab: 'starterPack',
    }),
    createStep({
      id: 'starter-pack-demo-3-send',
      title: '示例三 · 发送',
      description: '点选示例后副窗会自动收起',
      targetSelector: '#sendMessageBtn',
      actionType: 'click',
      routeName: 'chat',
    }),
    createStep({
      id: 'starter-pack-demo-3-confirm-task',
      title: '示例三 · 确认任务',
      description: '「增加发货单」与生成类示例相同：主操作在右侧任务面板',
      targetSelector: '#taskPanel button[data-action="confirm-task"]',
      highlightSelector: '#taskPanel button[data-action="confirm-task"]',
      actionType: 'click',
      routeName: 'chat',
    }),
    createStep({
      id: 'starter-pack-demo-3-start-print',
      title: '示例三 · 开始打印',
      description: '执行成功后，任务卡片会出现「下载发货单」与绿色「开始打印」',
      targetSelector: '#taskPanel button[data-action="start-print"]',
      highlightSelector: '#taskPanel button[data-action="start-print"]',
      actionType: 'click',
      routeName: 'chat',
    }),
    createStep({
      id: 'tab-push',
      title: '推送与微信消息',
      description: '请点击副窗顶部的「推送」标签',
      targetSelector:
        '[data-tutorial-spotlight="assistant-panel"] .assistant-tab[data-tutorial-id="tab-push"]',
      actionType: 'click',
      routeName: 'chat',
      assistantTab: 'push',
    }),
    createStep({
      id: 'wechat-contacts-stars',
      title: '微信与星标联系人',
      description: `请点击侧栏「${dataSourcesLabel}」，在页面中选择「微信本地…`,
      targetSelector: '.sidebar .menu-item[data-view="data-sources"]',
      actionType: 'click',
      routeName: 'chat',
      assistantTab: 'push',
      allowCardNext: true,
    }),
    createStep({
      id: 'wechat-starred-list-intro',
      title: '星标联系人列表',
      description: '下方卡片为「星标联系人列表」：可筛选类型（全部/联系人/群聊）、在列表中搜索…',
      targetSelector: '#view-data-sources [data-tutorial-id="wechat-starred-list"]',
      highlightSelector: '#view-data-sources [data-tutorial-id="wechat-starred-list"]',
      actionType: 'observe',
      routeName: 'data-sources',
    }),
    createStep({
      id: 'chat-star-auto-refresh',
      title: '星标聊天自动刷新',
      description: `请先点击左侧「${chatLabel}」回到本页（若已在对话页可忽略）`,
      targetSelector: '#view-chat label[data-tutorial-id="star-auto-refresh-toggle"]',
      highlightSelector: '#view-chat label[data-tutorial-id="star-auto-refresh-toggle"]',
      actionType: 'click',
      routeName: 'chat',
    }),
    createStep({
      id: 'chat-excel-analyze-toolbar',
      title: '分析 Excel',
      description: '微信与星标相关流程后，可在智能对话输入区上方使用「分析Excel」：上传工作…',
      targetSelector: '#view-chat button[data-tutorial-id="toolbar-excel-analyze"]',
      highlightSelector: '#view-chat button[data-tutorial-id="toolbar-excel-analyze"]',
      actionType: 'click',
      allowCardNext: true,
      routeName: 'chat',
    }),
    createStep({
      id: 'chat-intent-pro-experience',
      title: 'AI意图体验（对话开关）',
      description: '工具栏上的「专业模式AI意图体验」用于增强对话里 AI 意图识别与回复方式（…',
      targetSelector: '#view-chat label[data-tutorial-id="intent-pro-experience-toggle"]',
      highlightSelector: '#view-chat label[data-tutorial-id="intent-pro-experience-toggle"]',
      actionType: 'observe',
      routeName: 'chat',
    }),
    createStep({
      id: 'tab-assistant',
      title: '产品协助',
      description: '请点击「协助副窗」，用于产品查询与资料修正。',
      targetSelector:
        '[data-tutorial-spotlight="assistant-panel"] .assistant-tab[data-tutorial-id="tab-assistant"]',
      actionType: 'click',
      routeName: 'chat',
      assistantTab: 'assistant',
    }),
    createStep({
      id: 'tab-one-click',
      title: '一键托管',
      description: '请点击「一键托管」，在「工作流员工选择」中用开关启用需要的 AI 员工。',
      targetSelector:
        '[data-tutorial-spotlight="assistant-panel"] .assistant-tab[data-tutorial-id="tab-one-click"]',
      actionType: 'click',
      routeName: 'chat',
      assistantTab: 'oneClick',
    }),
    createStep({
      id: 'tab-lobster',
      title: '龙虾托管',
      description: '请点击「龙虾托管」，同样可通过开关选择参与托管的 AI 员工。',
      targetSelector:
        '[data-tutorial-spotlight="assistant-panel"] .assistant-tab[data-tutorial-id="tab-lobster"]',
      actionType: 'click',
      routeName: 'chat',
      assistantTab: 'lobster',
    }),
    createStep({
      id: 'settings-entry',
      title: settingsLabel,
      description: `请点击侧栏底部「${settingsLabel}」，确认配置入口可正常访问`,
      targetSelector: '.sidebar .menu-item[data-view="settings"]',
      actionType: 'click',
      routeName: 'settings',
    }),
    createStep({
      id: 'sidebar-nav',
      title: '菜单总览',
      description: '最后浏览左侧菜单分区，确认常用入口可见且布局正常。',
      targetSelector: '.sidebar .sidebar-menu',
      actionType: 'observe',
    }),
  ]
}
