/**
 * 默认中文文案（zh-CN 语言包通过 vue-i18n 引用本对象）
 */

export const zhIntro = {
  app: {
    apiHealthWarn: 'MODstore API 已连接但健康检查未返回 ok。',
    apiConnFail:
      '无法连接 MODstore API（默认 127.0.0.1:8765）。请先在本目录运行 start-modstore.bat，或确认 Vite 已将 /api 代理到 modstore_server。',
  },

  appTagline: 'XCAGI 扩展包（Mod）的本地工作台：集中存放、编辑、校验，并与 XCAGI / FHD 对接。',

  navTitle: {
    library: 'Mod 库：查看库中全部扩展、导入导出与同步',
    author: '制作向导：manifest 字段说明、宿主 API 列表、蓝图约定',
    debug: '调试：沙箱目录、XCAGI 加载状态、单包推送',
    settings: '路径与同步：库目录、XCAGI 根、后端 URL、FHD 壳菜单导出',
  },

  navShort: {
    library: '库',
    author: '制作向导',
    debug: '调试',
    settings: '路径与同步',
  },

  common: {
    close: '关闭',
    langZh: '中文',
    langEn: 'English',
  },

  home: {
    title: 'Mod 库',
    leadBefore:
      '这里展示「library」目录下的全部 Mod：每个目录是一份带 manifest.json 的扩展包，可校验、编辑、导入 ZIP，并推送到 XCAGI 的 mods 由宿主启动时加载。若需中文说明各 manifest 字段、或合并宿主 OpenAPI 中的 /api 路由列表，请打开',
    leadAfter: '。',
    authorLink: '「制作向导」',
    leadTail:
      '推送到 XCAGI/mods 或调试页生成 XCAGI_MODS_ROOT 沙箱目录的用法不变。',
    monitorTitle: 'XCAGI 已接入',
    monitorSub: '当前 XCAGI 根下 mods 目录中的扩展包（与「推送」目标一致）',
    monitorPath: 'mods 路径',
    monitorEmpty: '暂无已部署的 Mod',
    monitorLoading: '扫描中…',
    monitorErr: '无法扫描',
    monitorPrimary: 'PRIMARY',
    monitorFooter: '进程内加载状态见「调试」页',
    currentPrimaryLabel: '当前主 Mod：',
    currentPrimaryLine: '{name}（{id}）',
    currentPrimaryNone:
      '未指定主 Mod：各 manifest 均未设置 primary: true。宿主侧栏/角标等「主扩展」依赖该字段，可在「调试」页一键设为 primary 或手动编辑 manifest。',
    currentPrimaryMany: '警告：有 {count} 个 Mod 同时标记 primary，请只保留一个为 true。',
    monitorCurrentTitle: '主扩展',
    gridHint: '点击卡片进入该校验与编辑页（与右侧「已部署」列表 id 一致时可对照 manifest）。',
    monitorRowLinkTitle: '在库中打开该 Mod 详情',
  },

  author: {
    fallbackPage:
      '本页展示写 Mod 时的字段约定与后端蓝图习惯写法。点击「合并宿主 /api 路由」后，会从「路径与同步」里配置的后端地址下载 openapi.json，并只列出 /api 前缀的路径，便于与自有蓝图对照。',
    manifestSection: '以下为 manifest 中常见字段的中文说明；「必填」标签表示校验强烈建议填写。',
    blueprintSection: '后端需实现约定入口：在 Python 模块中提供 register_blueprints(app, mod_id)，并由 manifest.backend.entry 指向该模块名。',
    openapiSection: '表格为宿主当前暴露的 HTTP 路由摘要；完整参数、请求体与鉴权请以宿主 /openapi.json 为准。',
    runtimeSection:
      '以下为部署目标、沙箱环境变量与 FHD 壳菜单导出等关键词，供复制到文档或脚本使用。',
    title: '制作向导',
    subHint:
      '请先于「路径与同步」填写宿主后端地址；再使用下方按钮刷新内置说明或合并 openapi.json 中的 /api 路由表。',
    btnRefresh: '刷新内置扩展面',
    btnMerge: '合并宿主 /api 路由',
    btnMergeLoading: '拉取宿主 OpenAPI…',
    loading: '加载中…',
    manifestTitle: 'Manifest 字段说明',
    blueprintTitle: '后端蓝图约定',
    openapiTitle: '宿主 API 摘要（OpenAPI）',
    openapiCount: '当前共 {n} 条路径（仅 /api 前缀）；完整定义见宿主 /openapi.json。',
    thPath: '路径',
    thMethod: '方法',
    hostOpenapiTitle: '宿主 OpenAPI',
    runtimeTitle: '运行与调试',
    requiredPill: '必填',
    examplePrefix: '例:',
    flashHostOpenapiFail: '内置扩展面已加载；宿主 OpenAPI 拉取失败（见下方）',
    flashMergedRoutes: '已合并 {count} 条 /api 路由',
  },

  settings: {
    lead:
      '「库根目录」即 MODstore 存放所有 Mod 源码的文件夹（默认项目内 library）。「XCAGI 根目录」用于 push/pull 时定位 XCAGI/mods。「后端 URL」供调试页与制作向导代理请求宿主接口。导出 FHD JSON 用于本仓库 FHD 壳层的 GET /api/mods 菜单数据。',
  },

  debug: {
    lead:
      '沙箱会在本机生成仅含单个 Mod 的 mods 目录；将环境变量 XCAGI_MODS_ROOT 指向该路径并重启 XCAGI 后端，即可在不污染主 mods 目录的情况下调试。下方 JSON 为宿主 /api/mods/loading-status 的代理返回。',
  },

  notFound: {
    lead: '您访问的地址没有对应页面。请从下方返回 Mod 库首页。',
  },

  modDetail: {
    overviewHint:
      '概览按模块展示：API 与后端入口、manifest 中的配置块、工作流员工、前端菜单。编辑基础信息请切到「编辑」；改完整结构请用「JSON」。',
    em: '—',
    back: '← 返回列表',
    loading: '加载中…',
    validationOk: '校验通过',
    validationWarn: '有警告',
    exportZip: '导出 ZIP',
    pushXcagi: '推送到 XCAGI',
    delete: '删除',
    warningsTitle: '校验提示',
    tabsAria: 'Mod 详情分区',
    tabOverview: '概览',
    tabEdit: '编辑',
    tabJson: 'JSON',
    tabFiles: '文件',
    cardApiTitle: 'API 与后端',
    subHooks: 'Hooks',
    routesPrefix: '路由 · ',
    bpScanning: '扫描中…',
    thFunction: '函数',
    thPath: '路径',
    thMethod: '方法',
    bpNoRoutes: '未解析到 @route。',
    cardConfigTitle: '配置',
    configHintBefore: '宿主数据库连接在 XCAGI 环境；此处仅 manifest 内 ',
    configHintAfter: '。',
    noConfig: '无 config',
    cardWorkflowTitle: '工作流 / 员工',
    notConfigured: '未配置',
    cardMenuTitle: '前端菜单',
    thMenuId: '菜单 id',
    thMenuLabel: '文案',
    thMenuPath: '路径',
    thMenuIcon: '图标',
    noMenu: '无 menu',
    editBasicTitle: '基本信息',
    editHint: '复杂字段请用 JSON 页编辑。',
    labelId: 'id（与目录名一致）',
    labelVersion: '版本',
    labelName: '名称',
    labelAuthor: '作者',
    labelDescription: '描述',
    labelPrimary: 'primary（主 Mod）',
    btnSaveManifest: '保存到 manifest',
    jsonLabel: '完整 JSON（须保持 id 与目录名一致）',
    btnSaveJson: '保存 JSON',
    filesHint:
      '点击下列文本类文件可在线编辑（与后端白名单一致：.py .json .vue .ts .js .css .md .txt .html 等）。',
    noFiles: '无文件或未扫描到。',
    modalClose: '关闭',
    modalSave: '保存',
    modalSaving: '保存中…',
    msgSaved: '已保存',
    msgSavedWithWarnings: '已保存（仍有提示，见上方）',
    msgFileSaved: '文件已保存',
    msgSavedFileWarn: '已保存（manifest 提示：{hint}）',
    jsonParseErr: 'JSON 解析失败: {msg}',
    msgDeployed: '已部署: {list}',
    confirmDelete: '确定从库中删除 Mod「{id}」？不可恢复。',
    cardFhdTokensTitle: 'FHD 数据库令牌',
    fhdReadTokenLabel: '只读令牌（X-FHD-Db-Read-Token）',
    fhdWriteTokenLabel: '写入令牌（X-FHD-Db-Write-Token）',
    fhdTokensHint:
      '与 FHD 环境变量 FHD_DB_READ_TOKEN / FHD_DB_WRITE_TOKEN 对应；保存在 manifest.config，部署后由宿主或脚本同步到环境。请勿提交到公开仓库。',
    fhdTokenSet: '已设置（{n} 字符）',
    fhdTokenUnset: '未设置',
    fhdColManifest: '随 Mod（manifest.config）',
    fhdColHost: '宿主 FHD（环境变量）',
    fhdHostReadYes: '只读：已配置',
    fhdHostReadNo: '只读：未配置',
    fhdHostWriteYes: '写入：已配置',
    fhdHostWriteNo: '写入：未配置',
    fhdHostFetchErr: '无法拉取宿主状态（请检查「路径与同步」后端 URL 是否为 FHD :8000）',
    cardWalletTitle: '钱包密钥',
    walletSecretLabel: '密钥（API / 私钥等）',
    walletHint:
      '保存在 manifest.config.wallet_secret；由宿主或链上服务读取，勿提交到公开仓库。与 FHD 数据库令牌相互独立。',
    /**
     * 蓝图函数名 snake 片段 → 中文（供 vue-i18n，键为 intro.modDetail.bpSegments.<片段>）
     */
    bpSegments: {
      get: '获取',
      post: '提交',
      put: '更新',
      delete: '删除',
      patch: '局部更新',
      list: '列出',
      create: '创建',
      update: '更新',
      save: '保存',
      load: '加载',
      fetch: '拉取',
      sync: '同步',
      batch: '批量',
      process: '处理',
      smart: '智能',
      advanced: '高级',
      settings: '设置',
      dashboard: '仪表盘',
      home: '首页',
      index: '索引',
      detail: '详情',
      search: '搜索',
      export: '导出',
      import: '导入',
      upload: '上传',
      download: '下载',
      preview: '预览',
      validate: '校验',
      submit: '提交',
      cancel: '取消',
      confirm: '确认',
      reset: '重置',
      refresh: '刷新',
      status: '状态',
      health: '健康',
      user: '用户',
      users: '用户',
      mod: '扩展',
      mods: '扩展',
      menu: '菜单',
      routes: '路由',
      blueprint: '蓝图',
      api: '接口',
      webhook: '钩子',
      callback: '回调',
      shipment: '发货',
      created: '已创建',
      product: '产品',
      imported: '已导入',
      order: '订单',
      orders: '订单',
      price: '价格',
      contract: '合同',
      customer: '客户',
      customers: '客户',
      report: '报表',
      chart: '图表',
      data: '数据',
      file: '文件',
      files: '文件',
      config: '配置',
      init: '初始化',
      run: '运行',
      exec: '执行',
      handle: '处理',
      parse: '解析',
      build: '构建',
      merge: '合并',
      diff: '对比',
      log: '日志',
      error: '错误',
      debug: '调试',
      test: '测试',
      mock: '模拟',
      proxy: '代理',
      auth: '鉴权',
      login: '登录',
      logout: '登出',
      token: '令牌',
      session: '会话',
      cache: '缓存',
      queue: '队列',
      task: '任务',
      job: '任务',
      worker: '工作者',
      notify: '通知',
      message: '消息',
      send: '发送',
      receive: '接收',
      hook: '钩子',
      event: '事件',
      trigger: '触发',
      on: '当',
      off: '关闭',
      enable: '启用',
      disable: '禁用',
      check: '检查',
      apply: '应用',
      revert: '还原',
      clone: '克隆',
      copy: '复制',
      move: '移动',
      rename: '重命名',
      archive: '归档',
      restore: '恢复',
      purge: '清除',
      clean: '清理',
      optimize: '优化',
      migrate: '迁移',
      seed: '种子',
      backup: '备份',
      /* 常见路由名补充（缺任一片段会整名回退为原名） */
      active: '活跃',
      channels: '频道',
      recommend: '推荐',
      qa: '问答',
      package: '包',
      packages: '各包',
      phone: '电话',
      agent: '代理',
      typo: '笔误路径',
      start: '启动',
      stop: '停止',
    },
  },

  /** manifest_contract.fields[].kind 的简短标签（string[] 在 i18n 中用 stringList 键） */
  fieldKindLabel: {
    string: '文本',
    boolean: '是/否',
    array: '列表',
    object: '对象',
    stringList: '文本列表',
  },
}
